import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{background:"teal" , width:"100%", color:"#fff", padding:"25px"}}>
          <Link href="/articles" style={{ marginRight: "25px" }}>
            Articles
          </Link>

          <Link href="/posts">Post</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
